#include: package:flutter_lints/flutter.yaml
include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude: [build/**, lib/**.g.dart]
linter:
  rules:
    public_member_api_docs: false