name: demo
description: "Clean architecture example projet based"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  chewie: ^1.7.4
  cloud_firestore: ^4.13.6
  equatable: ^2.0.5
  fast_cached_network_image: ^1.1.1
  file_picker: ^6.1.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  firebase_ui_auth: ^1.7.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.4
  iconly: ^1.0.1
  icons_plus: ^5.0.0
  image_picker: ^1.0.5
  intl: ^0.18.1
  logger: ^2.0.2+1
  lottie: ^2.7.0
  objectbox: ^2.4.0
  objectbox_flutter_libs: any
  open_file: ^3.3.2
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  provider: ^6.1.1
  rounded_loading_button: ^2.1.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.5
  url_launcher: ^6.2.2
  uuid: ^4.3.3
  video_thumbnail: ^0.5.3
  youtube_metadata: ^1.0.1

dev_dependencies:
  analyzer: ^5.13.0
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  fake_cloud_firestore: ^2.4.5
  firebase_auth_mocks: ^0.13.0
  firebase_storage_mocks: ^0.6.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.3.0
  mock_exceptions: ^0.8.2
  mocktail: ^1.0.0
  objectbox_generator: any
  very_good_analysis: ^5.1.0

objectbox:
  output_dir: core/database

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/app/
    - assets/svg/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
