// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../src/auth/domain/entities/local_user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7489974916251087914),
      name: 'LocalUser',
      lastPropertyId: const IdUid(7, 219046075741983444),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1994844761155127579),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8352490072536372101),
            name: 'uid',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5556554992084341237),
            name: 'email',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5774105057489383868),
            name: 'fullName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4132687681854454027),
            name: 'points',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2034186240877078289),
            name: 'profilePicture',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 219046075741983444),
            name: 'bio',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 7489974916251087914),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    LocalUser: EntityDefinition<LocalUser>(
        model: _entities[0],
        toOneRelations: (LocalUser object) => [],
        toManyRelations: (LocalUser object) => {},
        getId: (LocalUser object) => object.id,
        setId: (LocalUser object, int id) {
          object.id = id;
        },
        objectToFB: (LocalUser object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final emailOffset = fbb.writeString(object.email);
          final fullNameOffset = fbb.writeString(object.fullName);
          final profilePictureOffset = object.profilePicture == null
              ? null
              : fbb.writeString(object.profilePicture!);
          final bioOffset =
              object.bio == null ? null : fbb.writeString(object.bio!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, fullNameOffset);
          fbb.addInt64(4, object.points);
          fbb.addOffset(5, profilePictureOffset);
          fbb.addOffset(6, bioOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final fullNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final profilePictureParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final bioParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final pointsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = LocalUser(
              uid: uidParam,
              email: emailParam,
              fullName: fullNameParam,
              id: idParam,
              profilePicture: profilePictureParam,
              bio: bioParam,
              points: pointsParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [LocalUser] entity fields to define ObjectBox queries.
class LocalUser_ {
  /// see [LocalUser.id]
  static final id = QueryIntegerProperty<LocalUser>(_entities[0].properties[0]);

  /// see [LocalUser.uid]
  static final uid = QueryStringProperty<LocalUser>(_entities[0].properties[1]);

  /// see [LocalUser.email]
  static final email =
      QueryStringProperty<LocalUser>(_entities[0].properties[2]);

  /// see [LocalUser.fullName]
  static final fullName =
      QueryStringProperty<LocalUser>(_entities[0].properties[3]);

  /// see [LocalUser.points]
  static final points =
      QueryIntegerProperty<LocalUser>(_entities[0].properties[4]);

  /// see [LocalUser.profilePicture]
  static final profilePicture =
      QueryStringProperty<LocalUser>(_entities[0].properties[5]);

  /// see [LocalUser.bio]
  static final bio = QueryStringProperty<LocalUser>(_entities[0].properties[6]);
}
